### PR TITLE
New Functionality of  FCM Editor

### PR DESCRIPTION
**Pull request by nrchaudhry**
Please review this and merge to master soon.

Also requested to update on the alpha server.

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
I cannot test it due to this error: https://github.com/policycompass/policycompass-fcmmanager/issues/5

**Comment by nrchaudhry** [comment]
Hi Fabian,

We changed the database schema, delete all fcm tables and update the FCM manager and then test frontend.

Best Regards

------- 
Nauman Riaz Chaudhry
PhD Scholar (Information Systems and Computing Research)
Department of Computer Science
School of Information Systems, Computing and Mathematics
Brunel University London
Uxbridge, Middlesex 
UB8 3PH, UK
Cell: +44 7538 402134
E-mail: nauman.riaz@gmail.com
nauman.chaudhry@brunel.ac.uk

**Comment by FabiApfelkern** [comment]
I did all this already.

**Comment by nrchaudhry** [comment]
Let me check.

Best Regards

------- 
Nauman Riaz Chaudhry
PhD Scholar (Information Systems and Computing Research)
Department of Computer Science
School of Information Systems, Computing and Mathematics
Brunel University London
Uxbridge, Middlesex 
UB8 3PH, UK
Cell: +44 7538 402134
E-mail: nauman.riaz@gmail.com
nauman.chaudhry@brunel.ac.uk

**Comment by nrchaudhry** [comment]
It is work fine locally

**Comment by FabiApfelkern** [comment]
I many tables are generated?

**Comment by nrchaudhry** [comment]
But it is working locally fine on my machine, what happen there? I pushed the same code on the git repo.

Have you update the hibernate.cfg.template.xml to hibernate.cfg.xml

**Comment by nrchaudhry** [comment]
Five tables.

**Pull request merged**
