### PR TITLE
improve maps charts policycompass/policycompass#335

### PR DESCRIPTION
**Pull request by mmilaprat**
This PR refers to issue 335 ( policycompass/policycompass#335)

It's to improve maps charts and also solve others issues like the start/end dates combos in the chart configuration.

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
The L.Control.Pan.js file, where is it from? Have you written it?

**Comment by mmilaprat** [comment]
No. I copy from here https://github.com/kartena/Leaflet.Pancontrol

**Comment by FabiApfelkern** [comment]
You need to put in the license.

**Comment by mmilaprat** [comment]
Do you mean to add a reference to it into the license.txt?

**Comment by FabiApfelkern** [comment]
I would put it into the js file itself. Is it not available on Bower?

**Comment by mmilaprat** [comment]
I think that it is not in bower

**Comment by mmilaprat** [comment]
then if I add a reference to the https://github.com/kartena/Leaflet.Pancontrol in the L.Control.Pan.js file, it's enough?

**Comment by cbotsikas** [comment]
@mmilaprat @FabiApfelkern As with npm, you can reference and install from github directly. 
In your case: 
bower install https://github.com/kartena/Leaflet.Pancontrol.git

**Comment by mmilaprat** [comment]
I prefer to set th js file as part of th visualisation module. If we need to update something will be easier.
Also we ave the scss files and images in diferent routes.

**Comment by cbotsikas** [comment]
here's the documentation: http://bower.io/docs/api/#install Check "Git endpoint" and "Git endpoint without .git" also "Git tag", "Git commit SHA" and "Git branch"

**Comment by FabiApfelkern** [comment]
@mmilaprat The rule is to always use bower for thirdparty libraries. If it is possible you should do it. I don't understand what is easier with downloading it manually?

**Comment by cbotsikas** [comment]
@mmilaprat "If we need to update something will be easier" are you editing the script? If not, you should use bower and if needed use tags or commit SHA to identify the working version. 
About the scss files, you should use the css provided, as we do with all bower components and if needed, override styles in PC's scss.

**Comment by mmilaprat** [comment]
I added the library in the bower.json file, update index.html to link to it, and I delete my version of L.Control.Pan.js

**Comment by mmilaprat** [comment]
now is better?

**Comment by cbotsikas** [comment]
@mmilaprat what's the difference of your [/app/sass/L.Control.Pan.scss](https://github.com/mmilaprat/policycompass-frontend/blob/map-improvement-1/app/sass/L.Control.Pan.scss) version compared to the [original L.Control.Pan.css](https://github.com/kartena/Leaflet.Pancontrol/blob/master/src/L.Control.Pan.css)?

**Comment by mmilaprat** [comment]
paths to the images that I added to the img folder

**Comment by cbotsikas** [comment]
ok, in this case you only need lines [83-94](https://github.com/mmilaprat/policycompass-frontend/blob/map-improvement-1/app/sass/L.Control.Pan.scss#L83-L94) from your scss, rename it to something like L.Control.Pan**.Fix**.scss and include the bower's css too.

**Comment by cbotsikas** [comment]
@mmilaprat wait! You don't even need that! just include the bower css and it should work. Your images are exactly the same to the origin ones. Do i miss something here?

**Comment by mmilaprat** [comment]
done

**Comment by mmilaprat** [comment]
ups
I read your message after do it

**Comment by mmilaprat** [comment]
I'm going to delete my .scss and the custom images

**Comment by mmilaprat** [comment]
I deleted the custom images and scss file. Now the css and image used are the "origianls"

**Comment by FabiApfelkern** [comment]
I get the error "Cannot read property 'value' of null" in a popup when using the map view.
Reproduce it:
- Browse to default Dataset 1
- Create a Visualization from it
- Click on "Map"

**Comment by mmilaprat** [comment]
I cannot reproduce it. Can you attach the console log error?
Dataset 1 is this, no?

Spain	39	127	158	181	124	82	45	76	50	48
Germany	744	662	702	632	756	680	716	865	827	774

**Comment by FabiApfelkern** [comment]
I started the console and now the error is gone. Strange. @cbotsikas Can you try this branch please? I want to make sure there is no error.
One question @mmilaprat Why is there a Copyright (Policy Compass (c)) next to Leaflet. This implies that wwe developed Leaflet or the maps.

**Comment by mmilaprat** [comment]
The text "Policy Compass ©" is something that I add to the map.

The Link "Leaflet" is authomatic

**Comment by FabiApfelkern** [comment]
But why have you add this to the map? It is jsut wrong because we are not the copyright owners of the map.

**Comment by mmilaprat** [comment]
I deleted the "Policy Compass ©"  text

**Comment by cbotsikas** [comment]
works for me too

**Pull request merged**
