### PR TITLE
store visualisations preferences in cookie

### PR DESCRIPTION
**Pull request by mmilaprat**
This PR is to store visualisation preferences (checkboxes and som combos) in cookie

related issue policycompass/policycompass/issues/601

### CODE REVIEW

**Comment by mmilaprat** [comment]
commits c4e70b8 and 0dffc92 are related with issue 660 ( policycompass/policycompass/issues/660 )

**Comment by FabiApfelkern** [comment]
@mmilaprat At which point are the preferences stored? Only when I save one visualization?

**Comment by mmilaprat** [comment]
when you save or update a visualisation

**Comment by FabiApfelkern** [comment]
Thanks. Should be good enough.

**Pull request merged**
