### PR TITLE
Add comment count without formatting to browse

### PR DESCRIPTION
**Pull request by slomo**
This is a first draft to add a comment counter to the browse page.

### CODE REVIEW

**Comment by cbotsikas** [comment]
It's not comment_count anymore, its commentsCount. I'll add this on an upcomming PR.

**Comment by slomo** [comment]
You can't rename the variable since adhocracy will still attempt to write the old name. Also if this is an attempt to unify naming of objects members, I have to note that datasetmanager and metricsmanager use underscore and only some other services use camel case.

**Comment by cbotsikas** [comment]
how will adhocracy attempt to write the old name?

**Comment by cbotsikas** [comment]
this is the pr i mentioned earlier: https://github.com/policycompass/policycompass-frontend/pull/179

**Comment by slomo** [comment]
After a comment is added it will lookup the object from elastic search and write the new comment count to `comment_count`.

**Comment by cbotsikas** [comment]
You should use search manager to invoke reindex for the specific object eg: http://services-stage.policycompass.eu/api/v1/searchmanager/updateindexitem/metric/26

**Pull request closed without merging**
