### PR TITLE
Indicator event details

### PR DESCRIPTION
**Pull request by bullz**
This PR is to update the PC layout. 

Changes

<ul>
  <li>Event and indicator details pages</li>
  <li>General typographic improvements: fixed custom fontweights and fontstyles (not related to issues)</li>
  <li>Browse page category icons and colors (added small label)</li>
  <li>FCM: Recover Control symbols in FCM</li>
</ul>

/policycompass/policycompass#200 
/policycompass/policycompass#264 
/policycompass/policycompass#242

### CODE REVIEW

**Comment by mmilaprat** [comment]
we are working to try to solve the conflicts

**Comment by mmilaprat** [comment]
wait to accept the pull request, we have a problem with a css file

**Comment by cbotsikas** [comment]
@mmilaprat I'm not confident about merging this PR because I don't really like the way it was resolved, especially with the first two "resolve conflicts" commits (https://github.com/bullz/policycompass-frontend/commit/275abce21a031a7c4642c88c4afe47ece543f55c and https://github.com/bullz/policycompass-frontend/commit/1e912af4ed34006f2538152235346fea505f9ea8) which IMHO they add unnecessary history changes to the affected files.. 
The following picture shows on the left how the git log should look like if you had properly merged master to your branch, and on the right you can see this PR's git log. I'm guessing that you tried to manually copy the changes to your branch and committed them with the first commit, then fixed the indention with the second commit and then merged the master with your last commit (actually i can't even reproduce your last commit so i'm not sure how it was done).

How you should have fixed this PR from your branch:
*git pull "origin" master
*(edit resolving the conflicting files, in your case: app\modules\search\partials\browse.html)
*git add app\modules\search\partials\browse.html
*git commit
Note: "origin" remote in this example is the policycompass (https://github.com/policycompass/policycompass-frontend) and should be changed with whatever you named it

Read more: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

How you can fix this PR:
Reset your branch to commit c613742 (git reset --hard c613742df6d9a20399f79c1ea0aee6eae955a572) and follow the above instructions. Doing so you'll change your branch history so you'll need to force the push to your github fork (be extremely careful not to force it to policycompass account).
If you don't feel confident doing so, we can either ignore my comment and proceed merging it as is or if you want, finish with your changes (you mentioned that you need to fix some css) and let me know so that i can manually fix and merge it to the master.

capture

@nidico @slomo do you have any comments?

**Comment by cbotsikas** [comment]
Also, for future commits, on the commit message start with a short description (like you did with this PR's message) so that it's easier for whoever is reviewing your PR to understand what's changed and then on the 2nd line put the issue id without the first slash so that github can understand and automatically link to it like this:
policycompass/policycompass#200 
policycompass/policycompass#264 
policycompass/policycompass#242

the syntax is username/repository#issue_number and apparently github doesn't like it when it has the slash or anything else in front of it.

**Comment by mmilaprat** [comment]
we still working to try to solve the merge correctly

**Comment by mmilaprat** [comment]
As we have problems to merge, we close this. we are going to create new PR.

**Comment by cbotsikas** [comment]
@mmilaprat @bullz do you want me to create a new up-to-date branch in PC including your https://github.com/bullz/policycompass-frontend/commit/275abce21a031a7c4642c88c4afe47ece543f55c and https://github.com/bullz/policycompass-frontend/commit/1e912af4ed34006f2538152235346fea505f9ea8commits so that can work with it to fix the css and PR that branch?

**Comment by mmilaprat** [comment]
no, because we are going to split this PR in 3, one per FCM issue, one per new items layout and one per new browse layout.

**Pull request closed without merging**
