### PR TITLE
/policycompass/policycompass#97 /policycompass/policycompass#108 /pol…

### PR DESCRIPTION
**Pull request by bullz**
…icycompass/policycompass#118

### CODE REVIEW

**Comment by mmilaprat** [comment]
This merge has:
a new loading page

update styles of common elements like buttons, links, ....

resolution issue /policycompass/policycompass#97
https://github.com/policycompass/policycompass/issues/97

resolution issue /policycompass/policycompass#108
https://github.com/policycompass/policycompass/issues/108

resolution issue /policycompass/policycompass#118
https://github.com/policycompass/policycompass/issues/118

template for upload datasets (step 1 and step 2)

**Comment by FabiApfelkern** [comment]
The merge conflict is my fault, but I pulled it locally and it is not working.
Do I have to do anything more, besides bower install.
I see the new fancy loading indicator but it never disappears....

**Comment by cbotsikas** [comment]
IMO, loading status should be inside index.html, visible by default, independant of any javascript. Having it in a partial, waiting for angular to load it defeats the purpose of having the loader indicator.

If we just need it for the initial loading indication, then you just need the plain jQuery onLoad way to remove it, aka: $(function () { //hide the element });

If you need to show this loader multiple times, you can use ng-hide.

**Comment by FabiApfelkern** [comment]
I agree. The initial loading indicator is not correct like this. Probably more research is necessary to do this properly. If you don't find an immediate solution, remove it for this pull request.

**Comment by cbotsikas** [comment]
policycompass/policycompass/73 is related. Adding it for reference.

**Comment by cbotsikas** [comment]
policycompass/policycompass#73 is related. Adding it for reference.

**Comment by mmilaprat** [comment]
Hi,
yesterday the loading indicator has been updated. Now there is a controller that with a jquery hide a div.

Are you refering to this one or at the previos one?

**Comment by cbotsikas** [comment]
I'm referring to the new one. The request for the loading indicator's partial is executed after ~13.4s which means, after the browser has loaded and parsed all PC scripts and css files and after the angular app has initialized. In order to avoid this, loading indicator must be placed within index.html without any relation to angular. You only need to hide/remove the element when the application is initialized. 

The first implementation was "wrong" because you should never use window.onload = function(){}. The proper plain JS way would be using Event Listeners. For simplicity, with jQuery, $(function () { });

**Pull request merged**
