### PR TITLE
Add "save to copy" to metrics edit

### PR DESCRIPTION
**Pull request by slomo**

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
This crashes somehow my browser (Firefox). When I try to edit a metric which is not mine the browser freezes.

**Comment by FabiApfelkern** [comment]
```
Error: object is undefined
Auth.state.isCreator@http://localhost:9000/app/modules/auth/services/auth.js:49:25
gb.prototype.functionCall/<@http://localhost:9000/bower_components/angular/angular.min.js:178:66
hb["!"]@http://localhost:9000/bower_components/angular/angular.min.js:162:88
gb.prototype.unaryFn/<@http://localhost:9000/bower_components/angular/angular.min.js:171:293
hb["&&"]@http://localhost:9000/bower_components/angular/angular.min.js:161:421
gb.prototype.binaryFn/<@http://localhost:9000/bower_components/angular/angular.min.js:171:508
hb["&&"]@http://localhost:9000/bower_components/angular/angular.min.js:161:421
gb.prototype.binaryFn/<@http://localhost:9000/bower_components/angular/angular.min.js:171:508
Yd/this.$get</h.prototype.$digest@http://localhost:9000/bower_components/angular/angular.min.js:110:236
Yd/this.$get</h.prototype.$apply@http://localhost:9000/bower_components/angular/angular.min.js:113:360
m@http://localhost:9000/bower_components/angular/angular.min.js:72:452
w@http://localhost:9000/bower_components/angular/angular.min.js:77:463
ye/</B.onreadystatechange@http://localhost:9000/bower_components/angular/angular.min.js:79:24

http://localhost:9000/bower_components/angular/angular.min.js
Line 92
```

**Comment by slomo** [comment]
Well I guess that only occurs in some race condition between data loading and rendering, could you try again?

**Comment by FabiApfelkern** [comment]
I tried it several times. It happens every time. My setting is that I have local installation of Policy Compass but I'm using A3 remotely from stage.

**Pull request merged**
