### PR TITLE
directive to unify common detail data

### PR DESCRIPTION
**Pull request by mmilaprat**
PR related wit issue policycompass/policycompass/issues/500

This PR create the new directive and it is used in to the visualisations, datasets, events, indicators, and metrics detail page.

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
Can you use a templateUrl and not a inline template in the directive?

**Comment by mmilaprat** [comment]
yes, I'm going to update code

**Comment by mmilaprat** [comment]
done

**Comment by FabiApfelkern** [comment]
Thanks. I will review in more detail tomorrow.

**Comment by mmilaprat** [comment]
@FabiApfelkern have you had time to check it?

**Comment by FabiApfelkern** [comment]
@mmilaprat I need more time for this one. I want to apply to one of my detail pages.

**Comment by mmilaprat** [comment]
@FabiApfelkern , has you got time to check it?

**Pull request closed without merging**
