### PR TITLE
Visualisations updates auth

### PR DESCRIPTION
**Pull request by mmilaprat**
This PR is to add auth into the deatail page.

Only admin users or creator can edit delete policycompass/policycompass/issues/96 
Logged users can "copy"
Guest can "play" but cannot save policycompass/policycompass/issues/340
Add new fields,  location and policy compass to the visualisation form. 

Also the top link in the home has been updated issue  policycompass/policycompass/issues/267 

This PR is related with a BE PR policycompass/policycompass-services/pull/80

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
I merged it, because we have a tight schedule. But I discovered a big issue with our Auth Service in this PR. In this line [1] the state of the user is checked and saved in a variable, which used in the template to activate or deactivate the save button. But if you load the page, e.g. with complete refresh, the call to the auth backend may be not complete yet. So the user state is unknown, but maybe he is logged in. We do need a promise on the Auth service, to set such variable async. I had a quick look in the Auth service, but I didn't found an easy solution to include such a promise (with $q). @nidico @MagdaN  Do you have an idea?

[1] https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/visualization/controllers/visualizationControllers.js#L5649

**Comment by FabiApfelkern** [comment]
I found an simple workaround for now. Directly using the Auth service in template. @mmilaprat Please adjust other places where you work with the user state.
But still we need a promise for the case one want to work with it in a controller.

**Comment by mmilaprat** [comment]
I use user.state.userPath and user.state.isAdmin in the directive to control if the current user can do an update of the visualisation that he is editing (is admin or is the author) or if he must create a new one (he is another user), but in this moment the auth backend is loaded.

**Comment by FabiApfelkern** [comment]
@mmilaprat 
Can you be more specific and give some links. Where do you use the user object, in which directive? Why so think it is already loaded?

**Comment by mmilaprat** [comment]
sorry, I use user.state.userPath and user.state.isAdmin in the visualisation controller, not in a directive.

**Comment by FabiApfelkern** [comment]
ok, but as I stated before, you can not be sure those values correctly loaded already in a controller. Have you seen this PR https://github.com/policycompass/policycompass-frontend/pull/224. I have fixed an issued with such an use in a controller there.

**Comment by mmilaprat** [comment]
But I use when user push the "save" button, in that moment user is logged

**Comment by FabiApfelkern** [comment]
Ok. I understand. Thank you. I just wanted to make sure.

**Pull request merged**
