### PR TITLE
Initial Loading indicator

### PR DESCRIPTION
**Pull request by FabiApfelkern**
https://github.com/policycompass/policycompass/issues/73

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@cbotsikas Can you check this out please?

**Comment by FabiApfelkern** [comment]
@cueneythizli Will implement it differently.

**Comment by FabiApfelkern** [comment]
@cbotsikas Can you please review this?

**Comment by th0br0** [comment]
Users with JS disabled will never see the page. Could we add a <noscript> tag?

**Comment by FabiApfelkern** [comment]
Good idea. I will do that,

**Comment by cbotsikas** [comment]
@FabiApfelkern I've added the noscript warning and changed the implementation using pure angular. Check: https://github.com/policycompass/policycompass-frontend/pull/348

**Pull request merged**
