### PR TITLE
FCM concepts nodes enhancement

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/issues/530
policycompass/issues/510

### CODE REVIEW

**Comment by mohammedbahja** [comment]
@cbotsikas I have noticed  that the tool-tip functionality is working on Edit mode but not in view mode, I need to check this. Anyway, I hope if this will be merged to be tested with the models on stage server which contain  too many nodes.

**Comment by cbotsikas** [comment]
@mohammedbahja I cannot merge this since it includes [FCM Authentication PR commits](https://github.com/policycompass/policycompass-frontend/pull/371) which i guess will break FCM if the backend isn't updated. Is that correct?

**Comment by mohammedbahja** [comment]
@cbotsikas hmm I am not sure to be honest, the saving functionality defiantly will not work. Anyway, it's better to wait but I'll continue pushing the new work here till the the back end get merged. I hope this branch will not make conflicts with policycompass/policycompass-frontend/pull/371

**Comment by mohammedbahja** [comment]
The tooltip has been added to the edit and view modes. However, I am having some issues with the tooltip position when the nodes  get zoomed in/out. I am fixing this .

**Comment by mohammedbahja** [comment]
It was returning wrong position from the directive. This has been fixed.

**Comment by mohammedbahja** [comment]
Tooltip position enchantment in case of too long title.

**Comment by cbotsikas** [comment]
https://github.com/policycompass/policycompass/issues/510
https://github.com/policycompass/policycompass/issues/530

**Pull request merged**
