### PR TITLE
plot x axis legend in middle of period

### PR DESCRIPTION
**Pull request by mmilaprat**
This PR adds an option in the visualisation form(only for line charts) that enable users to select where the x axis labels are plotted (at the beggining of the period or in the middle)

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@mmilaprat The options (Plot data and Plot x legend) are only visible when an event is present, is that correct? 
And I think the all those options in the grey box should be arranged more appealing. We should talk about it tomorrow.

**Comment by mmilaprat** [comment]
yes, this options only appears when there are some event

**Comment by FabiApfelkern** [comment]
why is that so?

**Comment by mmilaprat** [comment]
because the problem with "x labels" only appears after link some event to the chart

**Comment by FabiApfelkern** [comment]
The problem becomes more obvious with an event, but it is always there.

**Comment by mmilaprat** [comment]
If a visualisation don't have any related event, the problem does not appear.

**Comment by FabiApfelkern** [comment]
Can you explain why you think so? The question if a value is taken at the beginning or the end of a year is independent from events.

**Comment by mmilaprat** [comment]
if the chart don't display any event then you only view a line chart like this:

https://frontend-stage.policycompass.eu/app/#!/visualizations/29

Then is not important if we use the intial or the end of the period.

**Comment by FabiApfelkern** [comment]
Sorry, that is just not true. It is important. Lets discuss it tomorrow.

**Pull request merged**
