### PR TITLE
Replace nodejs custom written fileserver

### PR DESCRIPTION
**Pull request by slomo**
- replace custom file server by `node-static`
- drop proxies since all services support now cors

### CODE REVIEW

**Comment by cbotsikas** [comment]
Do not merge this PR yet. The assumption that all services support cors, is only valid when using the automated process with the makefiles that include proper configurations.

**Comment by slomo** [comment]
The `app/config.sample.js` also contains the direct path. I can't see what else, than writing an email afterwards I could do.

**Comment by cbotsikas** [comment]
Policy compass is not yet ready to handle the removal of the proxy pass. Since this code is not affecting the production servers but just the developer setup, i don't thing it's a good idea to remove it now. We need more time to test this PR before merging it to the master.

**Comment by slomo** [comment]
I tested this code on my local install (it works without starting nginx). Could you go a bit more into detail what you mean if you say not ready?

**Comment by cbotsikas** [comment]
Check today's wp3 mailing list, i concluded the issue with https://github.com/policycompass/policycompass/issues/284 and preparing a solution. 
I'm not confident that this is the only issue. If you are, go ahead and merge it..

**Comment by slomo** [comment]
I fixed this in pull-request #191 

Concerning other issues that might occur, I would like to go through with this one and fix all related errors. Otherwise it is kind of hard to get ever rid of all the nasty stuff.

**Comment by nidico** [comment]
> Concerning other issues that might occur, I would like to go through with this one and fix all related errors. Otherwise it is kind of hard to get ever rid of all the nasty stuff.

I second that motion.

**Pull request merged**
