### PR TITLE
#356 Automatic Switch to Results

### PR DESCRIPTION
**Pull request by FabiApfelkern**
https://github.com/policycompass/policycompass/issues/356

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@belalakbar It's working!

**Comment by belalakbar** [comment]
@FabiApfelkern 
is it update on liver server?
 second does the other tabs work properly when you click them such as click graph or they stuck.

**Comment by FabiApfelkern** [comment]
It is live now. Works fine for me.
Please remove those outputs: https://frontend-stage.policycompass.eu/app/#!/models/47/edit

**Comment by belalakbar** [comment]
ok

**Pull request merged**
