### PR TITLE
feature/carneades

### PR DESCRIPTION
**Pull request by th0br0**

### CODE REVIEW

**Comment by cbotsikas** [comment]
@th0br0 what editor are you using?
I don't really like how your editor is reformatting [bower.json](https://github.com/policycompass/policycompass-frontend/pull/294/files#diff-0a08a7565aba4405282251491979bb6b) and [app/modules/search/controllers/searchControllers.js](https://github.com/policycompass/policycompass-frontend/pull/294/files#diff-7e80dc1ceab36dd6ae6ec7bf5b6efa4c), both of them have been recently reformatted (https://github.com/policycompass/policycompass/issues/378)

also, what's the .tern-port file added in .gitignore?

**Comment by th0br0** [comment]
I've fixed the `bower.json` formatting; my default indentation was set to 2 spaces, not the 4 which is currently used in most places for this project.

As for the `searchControllers.js` formatting, I use spacemacs (an emacs distribution) which uses [js-beautify](https://github.com/beautify-web/js-beautify#options) under the hood... the settings for this could be adjusted globally, but there currently doesn't seem to be a styleguide for the javascript in this project.

**Comment by FabiApfelkern** [comment]
Please do not merge know. We want to review it in detail.

**Comment by FabiApfelkern** [comment]
@th0br0 Can you resolve the conflicts and fix the issue with the too big graph today?

**Comment by FabiApfelkern** [comment]
I'm not able to save Argument Graphs. There is a bug in the backend:

```
name 'CreateArgumentationGraphSerializer' is not defined
```

You haven't created any CreateArgumentationGraphSerializer. When I change it to "ArgumentationGraphSerializer" it works better, but I get "{"data": ["This field is required."]}2, although I have added a statement to the canvas.

**Comment by th0br0** [comment]
Yeah. Saving/Creating is still mostly untested / on my todo list

**Comment by FabiApfelkern** [comment]
Ah ok, I guess I will remove the Save button then.

**Pull request merged**
