### PR TITLE
/policycompass/policycompass#130

### PR DESCRIPTION
**Pull request by belalakbar**

### CODE REVIEW

**Comment by nidico** [comment]
Could you please write a proper title in the pull request? The reference to the issue solved can be written in the description.

**Comment by cbotsikas** [comment]
linking with the related issue https://github.com/policycompass/policycompass/issues/130

**Comment by belalakbar** [comment]
Can you suggest me how can I further proceed on it, because I did this work

**Comment by belalakbar** [comment]
Who will merge this pull reqeust?

**Comment by FabiApfelkern** [comment]
@belalakbar You have to resolve the conflicts first. Then we can merge it.

**Comment by belalakbar** [comment]
@ fabian, would you please guide me how resolve the conflicts, I am confused that how there is any conflict if the stage server is showing the changes under issue #129 130 and #122

further I have already deleted all the branches I created.

**Comment by FabiApfelkern** [comment]
You have to merge the master into your branch and resolve any merge conflicts.

**Pull request closed without merging**
