### PR TITLE
Front-end issues

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass/issues/611
policycompass/policycompass/issues/638
policycompass/policycompass-frontend/pull/456

### CODE REVIEW

**Comment by cbotsikas** [comment]
Are you keeping the simulation tab on Edit mode? What about the "Run Simulation" button on top menu?

**Comment by mohammedbahja** [comment]
@cbotsikas The simulation tab will stay in edit mode as well. The one in the top menu will be better if it  activates the the Run Simulation tab in the view mode in stead of pointing to the edit mode. I think this scenario is better. What do you think ?

**Comment by cbotsikas** [comment]
Is the simulation tab working for you, on view mode? For me it looks empty and none of the 3 buttons do anything
image

**Comment by cbotsikas** [comment]
I wouldn't keep the top menu button, but we can discuss this later when it's deployed on stage.

**Comment by mohammedbahja** [comment]
@cbotsikas you are right my friend, Simulation tab is not working in the view page. I checked this, it needs  time to be fixed also as you mentioned lets discussed this later. Right now I am working on the key words management service.

**Comment by cbotsikas** [comment]
i'm rejecting this PR. For https://github.com/policycompass/policycompass/issues/611, create a new PR

**Pull request closed without merging**
