### PR TITLE
/policycompass/policycompass#343

### PR DESCRIPTION
**Pull request by belalakbar**

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@belalakbar Please resolve the conflict.

**Comment by FabiApfelkern** [comment]
@belalakbar What about this one?

**Comment by belalakbar** [comment]
I will do this bit later. because other issue are main effecting the functionality.

**Comment by cbotsikas** [comment]
@belalakbar I'm fixing this now manually

**Comment by belalakbar** [comment]
@cbotsikas 
thanks

**Pull request merged**
