### PR TITLE
Added authentication for save model#330

### PR DESCRIPTION
**Pull request by vanaraj-zenex5ive**
Added authentication for save model

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
It would be great to have the button label be "Login to Save" when not logged in to make it clear for the user. It is done here: https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/indicators/partials/create.html#L23

**Comment by vanaraj-zenex5ive** [comment]
Hi Fabian,

I will add Login to Save button in the FCM models.

Regards,
Vanaraj.C

**Comment by vanaraj-zenex5ive** [comment]
Hi Fabian,

Do you need "Login to Save" button separately or it should replace "Save
Model"?

Regards,
Vanaraj.C

**Comment by vanaraj-zenex5ive** [comment]
@FabiApfelkern Added Login to Save label

**Comment by FabiApfelkern** [comment]
@vanaraj-zenex5ive Please resolve the conflicts

**Comment by FabiApfelkern** [comment]
I guess you misunderstood. I meant that the Save Button shows "Login to Save", not add an extra button. Please refer to the link I provided.

**Comment by aquinas9** [comment]
In the fcm editor, we have two button - "save" and "save as." and that's why we added additional button for that. One alternative is to hide one of them before user log-in. Let's see which one is better~!

**Comment by FabiApfelkern** [comment]
The the one is called "Login to Save" and the other one "Login to Save As", when not logged in. Like here https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/indicators/partials/create.html#L23

**Comment by aquinas9** [comment]
Okay, we will reflect it on early Monday.

**Comment by FabiApfelkern** [comment]
The "Login to Save" buttons should be active and have a link to the login page. Again refer to this: https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/indicators/partials/create.html#L23

**Comment by aquinas9** [comment]
@mohammedbahja 

Can you look on this issue as well?

**Comment by FabiApfelkern** [comment]
@mohammedbahja Is this PR still valid for you?

**Comment by aquinas9** [comment]
@FabiApfelkern 

At the moment, auth for saving models is implemented.
As we discussed in the telco, all action which make some data saved should be done after log-in.
In FCM, all saving data is evoked from run the simulation and simulation is needed the log-in for user. 

If you think my understanding is correct, you can merge this PR.

**Comment by FabiApfelkern** [comment]
This PR changes 28 files. That is to much. I guess somebody resolved conflicts the wrong way. I will close this. Please open a new pull request with just the changes need for the FCM auth,

**Pull request closed without merging**
