### PR TITLE
Please check and merge the changes from our designer

### PR DESCRIPTION
**Pull request by nadiapo**

### CODE REVIEW

**Comment by nidico** [comment]
Before looking at the actual code, there are two major issues which need to be resolved:

- This pull request commits many files which don't belong in the repo, e.g. `.sass-cache` and compiled `.css` files. They should be ignored using `.gitignore`.
- The pull request can't be merged due to conflicts. Please merge master in.

After fixing the issues you may want to squash the commits in order to not bloat the repository with the unwanted files.

**Comment by FabiApfelkern** [comment]
Thank you for the request, but I agree with @nidico, there are several things which need to addressed before reviewing the code.
- There are so many files, which don't belong into a Git repo. (cache, adobe files, ....)
- If we using SASS now, we should provide in properly via node, which have already included (e.g. https://www.npmjs.com/package/node-sass) and include instructions in the readme how to compile it to CSS. Don't provide the already compiled CSS files
- Don't include deprecated files, by renaming them *_old, or similiar. Please delete them.
- Why is there an PHP file? (app/colores.php)
- Please name everything in English (variables and files - e.g. app/css/colores.css)

**Comment by nadiapo** [comment]
Thank you for your comments. Will check with the designer, correct any problems and come back with a new pull request asap.

**Comment by mmilaprat** [comment]
Can you check it again?

**Comment by FabiApfelkern** [comment]
Thanks, but it is not sufficient yet.
- There are still files, where I think, they don't belong here:
  - app/css/bootstrap.css - We do have Bootstrap already via bower, don't put libraries in the repo!
  - app/fonts/edit/user notification.ai - This is an Adobe Illustrator file, isn't it?
  - app/fonts/edit/user notification.svg ???
  -  app/fonts/icomoon/Read Me.txt
  -  app/fonts/icomoon/demo-files/demo.css
  -  app/fonts/icomoon/...... Do we need every font?
  -  app/img/icon/create.ai
  -  app/img/icon/create2 copy-02.svg ??? A Copy?
  -  app/img/icon/iconos.ai
  -  I stop here, it is too much. Please clean it up.
- It is still not possible to merge automatically. Have you merged the master?
- As I mentioned before, if you use SASS it is best practice not to check in the created CSS files, but the SASS files, We all need to work with the Frontend and have to modify it, so we need to know how to do it. 
 - The user who made the commit is unknown? How have you pushed those commits to GitHub? Have you copied the repo from one machine to another?

**Comment by mmilaprat** [comment]
Hi,
some works has been done to solve the reported problems. Can you check it again?

About the sass and the css files. The idea is that if we need some css customisation of the new UI we must add it into the "css/custom.css" file. The other css files are only for the designer.

**Comment by FabiApfelkern** [comment]
Thank you!
I have had look and I deployed it to our new test server, so we can all evaluate it: https://frontend-stage.policycompass.eu
But, it is not ready for merging yet. There are still several issues:
 -  Still strange files in the repo:  app/modules/common/config.rb, pp/modules/events/partials/detail--new.html
 - I think we have some misunderstanding about the SASS thing here. Are you using SASS to generate CSS files? If yes, we all have to use it. How are we suppose to customize the CSS, e.g. when working on a specific page? The proper way is to only provide SASS files and no CSS file at all and each developer compiles the SASS to CSS. Do you have other opinions about that? 

- Small issues with the frontend itself, most obvious the icons are not working properly all the time. See screenshot.  

fail

**Comment by FabiApfelkern** [comment]
I got network errors too:

    "NetworkError: 404 Not Found - http://localhost:9000/app/modules/common/design.js"
    "NetworkError: 404 Not Found - http://localhost:9000/app/css/bootstrap.css"
    "NetworkError: 404 Not Found - http://localhost:9000/app/modules/common/design.js"

**Comment by almey** [comment]
I had a look on the new design in safari and I found two issues:

-	On the Main page the icons are appearing under each other rather then next to each other
bildschirmfoto 2015-05-06 um 11 37 40

-	On the Browse page there is a white box which is always visible under the search input field
bildschirmfoto 2015-05-06 um 11 37 56

**Comment by bullz** [comment]
Fixed issues:
<ul>
  <li>Added prefixes for safari</li>
  <li>Deleted unused files</li>
  <li>New font icon files</li>
  <li>Added sass files and instructions for compile .css thru sass</li>
</ul>

Please check new version

**Comment by FabiApfelkern** [comment]
Looks good. But I still have problem with the CSS files still present in the repo. In my opinion there shouldn't be any. The CSS folder should be in the gitignore and every CSS file is generated through SASS. In addition the README should be a little bit more detailed about how to compile SASS, not just telling about the watch command. Is it possible to have the compass config one folder up, so all commands can be executed in the root of this repo. 

@almey Can you please check this out on your Mac and test it on Safari again.

**Pull request merged**
