### PR TITLE
/policycompass/policycompass#101

### PR DESCRIPTION
**Pull request by mmilaprat**
move config.rb up (and update it).
delete app/css files
add a line in readme.md to advise to not update css files manually
delete reference to the "custom.css" in index.html
add folders to the .gitignore file

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
Are you sure you moved every css to sass? E.g. what what about this file: https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/common/css/offcanvas-filter.css

**Comment by mmilaprat** [comment]
the css and png (drop-bg.png) files from folders:

modules/common/css/
modules/common/css/
modules/common/css/
modules/metrics/css/
modules/datasets/css/
modules/fcm/css/

has been moved th the sass folder (and renamned to scss) .The new path to the background-image (drop-bg.png) has been addded in the sass files

the index.html has been updated to set the new css paths.

**Comment by FabiApfelkern** [comment]
Looks good! But the background images on the "How it works" page are not loading. Please correct this, check for other images which are maybe not loading and then you can merge it by your own. 
And it would be great if you can write an email to inform about this major change.

**Comment by mmilaprat** [comment]
Merged

**Pull request merged**
