### PR TITLE
Create share/embed modal window #154

### PR DESCRIPTION
**Pull request by bullz**
On visualization pages new buttonbar share option
No really modal but submenu type, because each social share API opens modal itself, so it would be redundant

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
Conflicts needs to be resolved.

**Comment by cbotsikas** [comment]
@bullz appart from the conflicts, i don't know how 3 issues are related and included in 1 PR. Also the fact that the 3rd commit has "14 changed files  with 540 additions and 271 deletions." makes it really hard to see what was really changed for the actual issue.
For the https://github.com/policycompass/policycompass/issues/154 we can't and don't want to use mail so we don't need that option. We also need to display the embedable iframe code that's the reasson i described the modal window with the two sections. Any suggestions about that?

Also about the "each social share API opens modal itself, so it would be redundant", are you talking about browser popup windows (that's what i know is used) cause i was refering to a css modal window similar to the one they use at https://soundcloud.com/stream (click any "Share" button)

**Comment by nadiapo** [comment]
Looks like this

**Comment by bullz** [comment]
Conflicts fixed, and social icons modified: grey button look, removed mail and added VKontakte social button

**Comment by FabiApfelkern** [comment]
@bullz @mmilaprat I merged it, but I noticed that there are links with the old hashkey style in it. They won't work. Please use #!/ instaed of #/

**Pull request merged**
