### PR TITLE
update modal dataset selector policycompass/policycompass#405

### PR DESCRIPTION
**Pull request by mmilaprat**
This PR is to solve issue 405  policycompass/policycompass#405

Also has some improvments for charts (pie and bars)

Charts improvments:
- Pie and bards: legends
- Bars: x axis plots individuals by time

also update css tho show scroll in modal windows.

### CODE REVIEW

**Comment by mmilaprat** [comment]
Last commit is to add values to the sliders that appears into the pie and map charts.

**Comment by FabiApfelkern** [comment]
I have some small remarks:
- You should spellcheck you English texts. E.g "must be fulfilled" is wrong. 
-  "you must be logged (you are!!)" is not very elegant. Why to say that he has to be logged in, when he is already?
- Don't use so many exclamation marks (!!!!). One is enough. :)
- I think "Changes will not be applied until you click over the "Apply" button!!!" is not necessary. It is obvious that things will be applied when clicking on "Apply." English is also wrong
- Is it possible to apply the color without to click on "Choose"?

**Comment by mmilaprat** [comment]
Spellcheck an altert sentnce (you are!!) updated.

About "Choose" button, we can check if it's possible to do for next PRs

**Comment by FabiApfelkern** [comment]
Please create yourself a ticket for the "Choose" issue if you think it's a good idea.

**Pull request merged**
