### PR TITLE
populate country list on front end

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass#575

### CODE REVIEW

**Comment by mohammedbahja** [comment]
@FabiApfelkern could you please marge this? 
Thanks

**Comment by FabiApfelkern** [comment]
It's merged and deployed on stage: https://frontend-stage.policycompass.eu/

**Comment by mohammedbahja** [comment]
@FabiApfelkern many thanks, still showing the old version of code.

image

It should be like this 

https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/common/directives/search.js#L471

**Comment by FabiApfelkern** [comment]
Check again!

**Comment by mohammedbahja** [comment]
Many thanks

**Comment by mmilaprat** [comment]
it's possible that this updates causes problems in other places where we use this directive? as example into the visualisation form when you select a dataset.

**Comment by mmilaprat** [comment]
sorry, but after this update the dataset selector don't work in causal model neither into the visualisations forms

**Comment by mohammedbahja** [comment]
hmm, the dataset selector should works fine for both components but there is  something went wrong. I am fixing this. 

This is from my Localhost,

image

**Pull request merged**
