### PR TITLE
/policycompass/policycompass#257 and improvments rtelated with #197

### PR DESCRIPTION
**Pull request by mmilaprat**
visualisation layout form updates. 

related with issues policycompass/policycompass#257 and policycompass/policycompass#197

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
I wouldn't merge yet. See comments here: https://github.com/policycompass/policycompass/issues/264

**Comment by mmilaprat** [comment]
I do some layout updates taking in account   https://github.com/policycompass/policycompass/issues/264 

this version is just to harmonize, about the comments about events detail page, we're going to think how to improve it.

**Comment by mmilaprat** [comment]
@FabiApfelkern, can you validate this first harmonization version of the detail and form page of visualisations, indicators and events?

**Comment by FabiApfelkern** [comment]
bower install does not work without user input:
```
Unable to find a suitable version for spectrum, please choose one:
    1) spectrum#~1.3.4 which resolved to 1.3.4 and is required by angular-spectrum#0.0.1
    2) spectrum#1.5.0 which resolved to 1.5.0 and is required by angular-spectrum-colorpicker#1.2.0
```

**Comment by mmilaprat** [comment]
In this pull reqyest "angular-spectrum-colorpicker" has been deleted from the bower.json file.

Can you check if your bower.json is correct?

**Comment by mmilaprat** [comment]
The error appears because "angular-spectrum-colorpicker"  stills in the bower_components folder

to avoid the problem reported by @FabiApfelkern there are two options:
delete the bower_components folder
or execute "./node_modules/.bin/bower prune" 

Probably we can add "./node_modules/.bin/bower prune" to the Readme.

**Comment by mmilaprat** [comment]
@FabiApfelkern and I have doubts about how to proceed with this.

If you try to import modules with bower without delete the bower_components folder the error reported by Fabian appears, but if you delete the folder or launch "bower prune" we avoid this problem.

@slomo , how is the best way to proceed?

add an advice to the readme file that says "You must delete the bower_folder" before the bower install?

This pull request is pending to be accepted. Can you help us? We need to solve this issue an merge this request?

**Comment by mmilaprat** [comment]
@slomo, has you got time to check it? I wish to close this pull request.

**Comment by cbotsikas** [comment]
It's allways a good idea to run "bower prune" before "bower install" when someone is updating the sources via git pull. First of all, you should send an email to the mailing list to let everyone know how to handle this error (although they might have seen this conversation already) and I suggest that you add a simple note, after the installation instuctions, about the update instructions. 

Deleting the directrory does the trick too but needs to install all components and takes longer time to complete.

Commands like "Bower install" "compass watch" etc are ment for developers and we shouldn't care much about the user input issue. This is only issue for the automated server deployment in which case we need to update the makefile script at https://github.com/policycompass/policycompass/blob/master/Makefile#L82 to execute the prune command.

Better yet, we can make npm script commads (via package.json) or use grunt to handle the proper install/update process.

**Comment by mmilaprat** [comment]
then for this pul request, I add an advice into the readme file like this?

./node_modules/.bin/bower prune (to delete old dependencies)
./node_modules/.bin/bower install (to install dependencies)


it's enough?

**Comment by cbotsikas** [comment]
Yes. just add the prune command before the install command for both linux and windows, without the parenthesis note and that should be just fine.

**Comment by mmilaprat** [comment]
done

**Comment by slomo** [comment]
Sorry for responding so late, but I haven seen any of the mentions before. So I am totally okay with the current solution. I will provide a pull-request to the main repo adding this and the sass compilation.

**Comment by mmilaprat** [comment]
@FabiApfelkern  cannot merge, he is on holidays. About the frontend, we agree that events layout needs a revision that we are going to do after this pull request. In this pull request it's only a first harmonization of the item details pages.

**Comment by mmilaprat** [comment]
@slomo agrees that I can merge this pull request

**Comment by cbotsikas** [comment]
@slomo This last commit https://github.com/policycompass/policycompass/commit/da6ae7655e7ecbd1c5935c48633fe089193f4708 doesn't actually solve the problem, but suspends the user input and in this case it doesn't fix the conflict. You need to execute prune prior to install.

**Comment by mmilaprat** [comment]
I'm going to send an email to the wp3 list to advice people that they need to execute prune.

**Comment by slomo** [comment]
@cbotsikas This was never intended to fix it. I just disliked the old method. I will start on Monday to fix the frontend build code.

**Pull request merged**
