### PR TITLE
Fixing frontend issues

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass/issues/574
policycompass/policycompass/issues/611
policycompass/policycompass/issues/612
policycompass/policycompass/issues/614
policycompass/policycompass/issues/615
policycompass/policycompass/issues/616

I added those issues in one PR as some of them are little issues and somehow related to each other.

### CODE REVIEW

**Comment by mohammedbahja** [comment]
policycompass/policycompass/issues/613

**Comment by cbotsikas** [comment]
Fixed the conflict and merged it.
https://github.com/policycompass/policycompass/issues/611 is not resolved
https://github.com/policycompass/policycompass/issues/614 probably not resolved
https://github.com/policycompass/policycompass/issues/616 not sure

**Comment by mohammedbahja** [comment]
@cbotsikas I dont see the changes on the stage server, it seems this merging has not been deployed.

**Comment by cbotsikas** [comment]
@mohammedbahja it's now published on stage

**Pull request merged**
