### PR TITLE
(Datasetmanager) Redesigned Import From External Resources 

### PR DESCRIPTION
**Pull request by cueneythizli**

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@cueneythizli The external resource dropdown is not working in Firefox, only in Chrome! Please check it.

**Comment by cbotsikas** [comment]
@cueneythizli are there any pending changes? I can see some code added but not used anywhere.
Also, avoid using ng-show, prefer ng-if instead.

**Comment by FabiApfelkern** [comment]
@cbotsikas I don't understand your comment!?

**Comment by cbotsikas** [comment]
datasets/controllers/datasetControllers.js
[lines 377 - 399](https://github.com/policycompass/policycompass-frontend/pull/365/files#diff-4bb0120bb6e71333864af7268b652d8aR377) is this code used anywhere?
datasets/directives/eurostatImport.js
[lines 92-99](https://github.com/policycompass/policycompass-frontend/pull/365/files#diff-06958feedb794f2ed87925195b033a22R92) not used and there are existing ways to do this kind of trimming.

**Comment by FabiApfelkern** [comment]
ah ok. thanks.

**Comment by FabiApfelkern** [comment]
@cueneythizli Please update this again with the now working bootstrap dropdown, because now the select in the EDP search results is not working.

**Comment by FabiApfelkern** [comment]
And scale down the images. You don't use 500px images for menu icons.

**Pull request closed without merging**
