### PR TITLE
move to elastic search API + directives to plot charts

### PR DESCRIPTION
**Pull request by mmilaprat**

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
You included the Elasticsearch functionality into your controller. This makes a reuse of this nearly impossible. But e.g. FCM will need such functionality as well. You should consider to put into a directive, probably into the Common module. This would also increase the readability of your code.

**Comment by mmilaprat** [comment]
I'm going to uptade my fork. I will move the metric selector as directive into the common.

**Comment by FabiApfelkern** [comment]
Thank you! I tried it and it works good so far! But I think it can be improved a little bit more. 
 - Small Bug: var url = "/"+API_CONF.ELASTIC_INDEX_NAME+'/:type/_search'; is not working with our new remote service integration. You should use absolute URLs (e.g. ar url = API_CONF.ELASTIC_URL + "/" + API_CONF.ELASTIC_INDEX_NAME + '/:type/_search'; ':type/_search';)
- Or even better: Spiros already implemented a SearchService based on a Elasticseach Plugin (https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/search/services/searchService.js) You might just want to use that.
- You put your directive and factory into the controllers module of the common module. Our structure suggests that such module should be in the respective folder (e.g. common/directives/search.js)

I hope this is not to much!

**Comment by mmilaprat** [comment]
Hi,
I'm trying to use the SearchService based on a Elasticseach Plugin but the order by title doesn't work.

In the search section the sort parameter of the elastic search is like:
 var sort =     [{"id" : {"order" : "desc"}},"_score"];

I use:
var sort =     [{"title" : {"order" : "asc"}}];

any idea why it not works?

**Comment by mmilaprat** [comment]
I update the code to use SearchService, but the sort by title doesn't work fine.

I also create the "common/directives/search.js" file to put the code.

**Comment by FabiApfelkern** [comment]
Have you contacted Spiros (@smouzakitis) about the title issue?

**Comment by smouzakitis** [comment]
Hi all, i have just send an email to Miquel about this. As i am currently traveling I expect to investigate this on Friday. But in general string sorting requires a bit of special treatment (http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/multi-fields.html)

**Comment by smouzakitis** [comment]
Hi Miquel, sorting by title should be working now (1e411d81fb00a4b515a8738c8fb0b6c1ba2a672b)

1) Get the latest code from the backend (git pull)
2) Then delete the current index by running the following command at prompt:
curl -XDELETE http://localhost:9200/policycompass_search
 (assuming localhost:9200 is your elasticsearch server)

3)Run rebuild index ("python manage.py rebuild_index")
4)For the sort field, instead of title, you should put "title.lower_case_sort" . See my https://github.com/policycompass/policycompass-frontend/commit/294134bb9269ee402a7b46285e8422a5da79c1ef for an example

let me know if it works ok

**Comment by mmilaprat** [comment]
I update to sort by title correctly and I added new directives to plot charts

**Pull request merged**
