### PR TITLE
Adding more question marks help modals to improve FCM help 

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass#454

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@mohammedbahja When I use the help popup for Weight it does not pop up at the same place but a couple of cm above. Is that on purpose?

**Comment by mohammedbahja** [comment]
@FabiApfelkern It appears in fixed position for no purpose. Do I need to change this to be in the same place?

**Comment by FabiApfelkern** [comment]
I'm not sure, but it makes sense to have the popup always next to the question marks, doesn't it?

**Comment by mohammedbahja** [comment]
Ture, I am working on it, I'll push the code in a bit.

**Comment by FabiApfelkern** [comment]
@mohammedbahja Is this PR still valid?

**Comment by mohammedbahja** [comment]
This has been fixed in policycompass-frontend/pull/361
No need for this PR

**Pull request closed without merging**
