### PR TITLE
Visualization directive

### PR DESCRIPTION
**Pull request by cbotsikas**

### CODE REVIEW

**Comment by cbotsikas** [comment]
I did the reformat, in separate commits, cause my IDE was automatically trying to fix the format with my actual changes.

**Comment by cbotsikas** [comment]
@FabiApfelkern you can use this directive to inject a visualization. 
I've found that there's is a conflict when you load more than one line chart in the same page. I haven't traced the issue yet. 
Maybe @mmilaprat can help. I'm guessing that the chart element ids or selectors are conflicting. The issue doesn't exist when you use "small" attribute on my directive.
Already fixed an issue with map charts where i found a ["loose selector"](https://github.com/cbotsikas/policycompass-frontend/blob/master/app/modules/visualization/js/objectMapLeflet.js#L22) that wouldn't allow multiple map charts and i also had to move the controller information from the partial to the directive in order to control the desired visualization Id (the original controller is reading the id from routeParams).

**Comment by mmilaprat** [comment]
@cbotsikas why you don't have id when you use "small" in the new directive?
An example of multiple line charts with small attribute are here https://frontend-stage.policycompass.eu/app/#!/events/26

**Comment by mmilaprat** [comment]
@cbotsikas , after read again your comment I catch you. When we use "small" the checkbox are not displayed. The idea of the "small" was to be used to plot related visualisations in events. I'll check if its possible to add multiple charts without "small" but I'm not sure.
As I understand, I think that we are going to add visualisations as "images" in the histories not as "interactive" charts.

**Comment by FabiApfelkern** [comment]
Works fine for me. @mmilaprat Are Christos changes affecting the core visualization functions at all? I would merge it then, so we can continue with the story manager.

**Comment by mmilaprat** [comment]
I think that you can merge it

**Comment by mmilaprat** [comment]
PR policycompass/policycompass-frontend/pull/487 solves issues that appears when you use this directive to plot n charts in the same page

**Pull request merged**
