### PR TITLE
Redesign Landing Page

### PR DESCRIPTION
**Pull request by mmilaprat**
PR with the new landing page

issue related policycompass/policycompass/issues/478

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
Do not merge yet, I need to review in detail.

**Comment by mmilaprat** [comment]
Please, don't merge it, I'm going to update it with minor changes (some labels, some linkd, scroll speed)

**Comment by FabiApfelkern** [comment]
No worries, I won't merge it. We have to discuss a lot about it. :)

**Comment by mmilaprat** [comment]
a lot? :-(

**Comment by FabiApfelkern** [comment]
Sure :)

**Comment by mmilaprat** [comment]
This is a new version of the landing page (In the commit f686395 I uploaded by mistake a sass folder with their content that I deleted in the commit 9cf5c79). 

About the issues reported in policycompass/policycompass/issues/478, the point "The Create, Browse and Request buttons should be incorporated into the steps and should have a mascot too" is missing. We are working on it.

But @FabiApfelkern, can you check if we are closed to your idea?

**Comment by FabiApfelkern** [comment]
@mmilaprat It's getting much better! I merged it for now, so everybody can review. I will write some feedback here: https://github.com/policycompass/policycompass/issues/478

**Pull request merged**
