### PR TITLE
Change mouse pointer when mouseover a node.

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass#456

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
I'm not that happy with two things:
 - It is very unexpected to have a cross when hovering over dragable element, shouldn't it be a hand?
 - It is also very uncommon to use double click in a web application, I just knew it because it is in the issue description. I guess any normal user wouldn't find it.

**Comment by medh15** [comment]
Many thanks Fabian for your comments.

- For the first one, yes I see that should be a hand.  

- For the second, we discussed this in Madrid and it's one of the comments that has been raised. 

@aquinas9

**Comment by FabiApfelkern** [comment]
Yes, we discussed it in Madrid, but now that it is there I'm not sure. We can discuss it tomorrow in the telco.

By the way: Do you have two accounts on GitHub?

**Comment by medh15** [comment]
This is the only account that I have

**Comment by mohammedbahja** [comment]
Sorry about the confusions, this is the account that i should use. The other account i  created once to teach my student in the university. 
I'll see you tomorrow

**Comment by mohammedbahja** [comment]
@FabiApfelkern I have changed  the mouse cursor. Could you marge please.

**Pull request merged**
