### PR TITLE
add is_draft visualisation FE

### PR DESCRIPTION
**Pull request by mmilaprat**
This PR is to add the is_draf funtionality into the visualisation FE. 
Related issue policycompass/policycompass/issues/618

### CODE REVIEW

**Comment by cbotsikas** [comment]
I've merged this so that we can test it out. I think the UI needs some work.

**Comment by FabiApfelkern** [comment]
@mmilaprat Do we need to change the background color to yellow when selecting draft?

**Comment by mmilaprat** [comment]
it's to advise user (visually is clear) that the item is in draft, but it's a proposal.

**Comment by cbotsikas** [comment]
i don't like how everything is changing place due to padding. also the "draft" addition on the url should not be with the same font size. it looks like its part of the title.

**Comment by mmilaprat** [comment]
this is a proposal, probably a designer can improve it. If you prefer another background colors or other "users advices" (like the label Draft in the title) we can talk about it.

**Comment by cbotsikas** [comment]
yes miquel, i already wrote when i merged that the ui needs some work but didn't write any comments. we could have a talk tomorrow.

**Pull request merged**
