### PR TITLE
Fixing selecting one country from adataset 

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass#575

### CODE REVIEW

**Comment by mohammedbahja** [comment]
@FabiApfelkern Could you please merge this PR?

**Comment by FabiApfelkern** [comment]
@mohammedbahja I have the feeling you are testing your code on the stage system? I cannot merge and deploy always that quick.

**Comment by mohammedbahja** [comment]
@FabiApfelkern, I had to ask for 3 PR for this task because I changed common directive that affected other component and I had to fix it urgently. I hope you will be able to merge this one soon. 
Sorry for that and your help is appreciated!

**Comment by FabiApfelkern** [comment]
Deployed!

**Comment by mohammedbahja** [comment]
Many thanks

**Pull request merged**
