### PR TITLE
Rewrite login register flows

### PR DESCRIPTION
**Pull request by slomo**
- login directly from pc-frontend (no more iframe messaging needed for login and register)
- store session data in local storage
- set a3 session from pc-frontend
- works only with ~~liqd/adhocracy3#cc1963b973b92bfddeda9b33cf1f7d1d455ab033~~ 37b0b92ad14aaa5044ea3b0786cc29040ffb45de

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@slomo Is the required A3 version already deployed on Stage?

**Comment by slomo** [comment]
@FabiApfelkern no it is not

**Comment by FabiApfelkern** [comment]
Is it possible to deploy this version today? Or does it only work hand in hand with this PR? I don't have a local A3 installation.

**Comment by slomo** [comment]
I will deploy the new A3 version to stage  today.

**Comment by slomo** [comment]
Rebased this pull request onto newest master and updated A3 to required version.

**Comment by FabiApfelkern** [comment]
@slomo Can you deploy the A3 version to prod too?

**Pull request merged**
