### PR TITLE
Provide opengraph metatags

### PR DESCRIPTION
**Pull request by cbotsikas**
https://github.com/policycompass/policycompass/issues/160

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@cbotsikas It's on stage. But what is it exactly doing? I copied a dataset link to facebook, but it's just rendering the general meta data, no dataset details. Is there a way to test this?

**Comment by cbotsikas** [comment]
You can check the meta tags content change with browser's inspector as you navigate the app.
There is yet an other commit missing, due to stability issues, where i render the application on node server, using phantomjs, and serving the generated html to the bots.
It's improving the social media presence already, thus i pushed this part earlier. 
using the following directives you can set/change the metatags on each page
```
<update-meta property="og:title" content="Title"></update-meta>
<update-meta property="og:description" content="Description"></update-meta>

**Comment by FabiApfelkern** [comment]
I see in changing. But very slowly, maybe Facebook is not getting it. But thank you very much,

**Comment by cbotsikas** [comment]
facebook can't see the changes since it's not executing any javascript. This is why we need to render the page on the server and serve the html without any javascript included. Combining this PR with my ongoing work, facebook, twitter, etc will be able to fetch the modified data you see on your browser

**Comment by FabiApfelkern** [comment]
Great! Thanks.

**Pull request merged**
