### PR TITLE
changing IsDraft to is_draft

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass#659

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@mohammedbahja There are still some things missing here:
- The draft status is not indicated in the read view of the FCM
- You cannot change the draft status to public once saved as draft

**Comment by mohammedbahja** [comment]
@FabiApfelkern 

> The draft status is not indicated in the read view of the FCM

 Has been done 
  

> You cannot change the draft status to public once saved as draft

This logic is already there, you need to deploy the [back-end](https://github.com/policycompass/policycompass-fcmmanager/pull/44) to avoid any err.

**Comment by FabiApfelkern** [comment]
@mohammedbahja It's not working. I had already the latest backend. The isDraft property is there. 

`{
    "model": {
        "id": 18,
        "keywords": "",
        "userID": 1,
        "dateAddedtoPC": 1473778248507,
        "dateModified": 1473778248507,
        "viewsCount": 0,
        "userPath": "https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000005/",
        "isDraft": true,
        "derivedFromId": 0,
        "title": "vbae",
        "description": "gvbagerb"
    },`

**Comment by mohammedbahja** [comment]
@FabiApfelkern 
I can see that this output does not reflect the latest back-end  changes.
> { "model": { "id": 18, "keywords": "", "userID": 1, "dateAddedtoPC": 1473778248507, "dateModified": 1473778248507, "viewsCount": 0, "userPath": "https://adhocracy-frontend-stage.policycompass.eu/api/principals/users/0000005/", "isDraft": true, "derivedFromId": 0, "title": "vbae", "description": "gvbagerb" },

Are you sure that you use the back-end from this [PR](https://github.com/policycompass/policycompass-fcmmanager/pull/44) ?
Please see the recorded video from one of my Local Machines 
[https://www.dropbox.com/s/qh4sp9s3e1gw84o/2016-09-13_2231.swf?dl=0](url)

**Comment by FabiApfelkern** [comment]
@mohammedbahja Yes you are right. Sorry. I merged and deployed on stage. But there is another issue now: https://github.com/policycompass/policycompass/issues/671

**Pull request merged**
