### PR TITLE
Added close button for inline help icon

### PR DESCRIPTION
**Pull request by bullz**
help-close

Also added close div tags on fcm/partials/create.html

### CODE REVIEW

**Comment by cbotsikas** [comment]
This commit is only fixing the help popup for Datasets. Is this intentional? I would expect a complete one which would add the close button everywhere..

**Comment by cbotsikas** [comment]
I think that the close button icon is not well positioned. I would expect something like this:
capture4
Which was done disabling some css:
capture
capture2
capture3

**Comment by bullz** [comment]
Modified size and position of the close button
Use the code in "create dataset" (app/#!/datasets/create) as example for other pages

**Comment by mmilaprat** [comment]
As this PR has conflicts we create another PR (policycompass/policycompass-frontend/pull/214)

**Pull request closed without merging**
